apiVersion: v1
kind: Service
metadata:
  name: mongodb  # This name must match the serviceName in your StatefulSet
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None  # This should be set to None for a headless service
  selector:
    app: mongodb  # This should match the labels of the pods in your StatefulSet