apiVersion: apps/v1
kind: Deployment
metadata:
  name: dexter-chat-blocking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dexter-chat-blocking
  template:
    metadata:
      labels:
        app: dexter-chat-blocking
    spec:
      containers:
      - name: chat-blocking
        image: docker.io/sticknycu/dexter-chat-blocking:1.3
        ports:
        - containerPort: 9091
