version: '3.7'

services:
  mongo-1:
    container_name: mongo-db-1
    image: mongo:7.0
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/etc/mongo-keyfile"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: /etc/mongo-keyfile
      MONGODB_DATABASE: chats
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 1s
      start_period: 1s
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile
      - mongo1_data:/data/db
      - mongo1_config:/data/configdb

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - "8082:8081"
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo-db-1:27017/
      - ME_CONFIG_MONGODB_SERVER=mongo-db-1
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
    depends_on:
      - mongo-1


  keycloak_web:
    image: keycloak/keycloak:latest
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - "8081:8080"

  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  postgres_data:
  mongo1_data:
  mongo1_config:

networks:
  mongo-compose-network:
    driver: bridge