apiVersion: v1
kind: Service
metadata:
  name: dexter-api-gateway-service
spec:
  selector:
    app: dexter-api-gateway  # This must match the labels of the pods you want to target
  ports:
  - protocol: TCP
    port: 80                # The port the service will be accessed on
    targetPort: 3333        # The port on the pods to which traffic will be sent
  type: LoadBalancer        # Makes the service accessible externally through a cloud provider's load balancer
